version: 0.2

phases:
  install:
    commands:
      - npm install
      - cd app
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - - aws s3 rm s3://[s3のバケット名] --recursive
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'